version: '3.1'
services:
  stats-server:
    build: ./stats-server/
    image:  stats-server
    container_name: stats_docker
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-db
      - POSTGRES_USER=root_stats
      - POSTGRES_PASSWORD=password_stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_docker
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=stats-db
        - POSTGRES_USER=root_stats
        - POSTGRES_PASSWORD=password_stats

  ewm-service:
    build: ./ewm-service/
    image:  ewm-service
    container_name: ewm_docker
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm-db
      - POSTGRES_USER=root_ewm
      - POSTGRES_PASSWORD=password_ewm


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_docker
    ports:
        - "6542:5432"
    environment:
        - POSTGRES_DB=ewm-db
        - POSTGRES_USER=root_ewm
        - POSTGRES_PASSWORD=password_ewm
