version: '3.8'
services:
  stats-server:
    build: ./stats/
    image:  stats-server
    container_name: stats_docker
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

    environment:
        - DB_NAME=stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - DB_HOST=stats-db
        - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_docker
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm/
    image:  ewm-service
    container_name: ewm_docker
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server

    environment:
        - DB_NAME=ewm
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - DB_HOST=ewm-db
        - DB_PORT=5432
        - STATS_SERVER_URL=http://server:9090


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_docker
    ports:
        - "6542:5432"
    environment:
        - POSTGRES_DB=ewm
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
