--Статистические данные
CREATE TABLE IF NOT EXISTS statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar (20) NOT NULL, --Идентификатор сервиса для которого записывается информация
    uri varchar (512) NOT NULL, --URI для которого был осуществлен запрос
    ip varchar (512) NOT NULL, --IP-адрес пользователя, осуществившего запрос
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, --Дата и время, когда был совершен запрос к эндпоинту
    CONSTRAINT pk_statistics PRIMARY KEY (id)
);