
CREATE TABLE IF NOT EXISTS categorys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(512) NOT NULL,
    CONSTRAINT pk_categorys PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(512) NOT NULL,
    email VARCHAR (20) NOT NULL ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(512) NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(512) NOT NULL,
    annotation VARCHAR(512) NOT NULL,
    description VARCHAR(512) NOT NULL,
    category_id integer references categorys(id),
    initiator_id integer references users(id) ON DELETE CASCADE,
    location_id integer references locations(id),
    compilation_id integer references compilations(id),
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    state varchar (20),
    paid BOOLEAN NOT NULL,
    participant_limit integer,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    request_oderation BOOLEAN NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
    event_id integer references events(id) ON DELETE CASCADE,
    compilation_id integer references compilations(id) ON DELETE CASCADE,
    CONSTRAINT event_compilation UNIQUE (event_id, compilation_id)
);


CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id integer references events(id) ON DELETE CASCADE,
    requester_id integer references users(id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status varchar (20),
    CONSTRAINT pk_requests PRIMARY KEY (id)
);